# Generated by Django 5.0.3 on 2024-05-03 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pay', models.CharField(max_length=100)),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='company_images/')),
                ('link_to_apply', models.URLField(blank=True, null=True)),
                ('link_to_company', models.URLField(blank=True, null=True)),
                ('list_of_applicants', models.ManyToManyField(blank=True, related_name='applied_jobs', to=settings.AUTH_USER_MODEL)),
                ('skills_used', models.ManyToManyField(to='Core.resumeskills')),
            ],
        ),
    ]
