# Generated by Django 5.0.3 on 2024-05-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_resumeskills_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_image',
        ),
        migrations.AddField(
            model_name='job',
            name='company_image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
