# Generated by Django 5.0.3 on 2024-05-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0003_userprofile_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="skills",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
