# Generated by Django 5.0.3 on 2024-05-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0004_alter_userprofile_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="skills",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="skills",
            field=models.ManyToManyField(blank=True, to="Core.skill"),
        ),
    ]
