# Generated by Django 5.0.3 on 2024-05-02 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0005_skill_remove_userprofile_skills_userprofile_skills"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill",
            new_name="UserSkill",
        ),
    ]
