# Generated by Django 5.0.3 on 2024-05-07 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_employerprofile_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Searcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searcher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('Offer', 'offer'), ('Reject', 'reject'), ('Interview', 'interview'), ('Pending', 'pending')], max_length=50, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.job')),
                ('job_searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.searcher')),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='list_of_applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to='Core.searcher'),
        ),
    ]
