# Generated by Django 5.0.3 on 2024-05-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0006_rename_skill_userskill"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="goal",
            field=models.TextField(blank=True, null=True),
        ),
    ]
