# Generated by Django 5.0.3 on 2024-05-03 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0007_userprofile_goal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="goal",
        ),
    ]
